const APP_KEY="neurorehabDoseTracker.v3";
const $=id=>document.getElementById(id);
const N=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const E=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const uid=p=>crypto?.randomUUID?`${p}-${crypto.randomUUID()}`:`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const ago=d=>{const x=new Date();x.setDate(x.getDate()-d);return x.toISOString().slice(0,10)};
const fmt=d=>d?new Date(d+"T12:00:00").toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}):"No date";
const avg=a=>{const c=a.map(Number).filter(Number.isFinite);return c.length?c.reduce((x,y)=>x+y,0)/c.length:0};
const pct=(v,t)=>t?Math.max(0,Math.min(100,Math.round(N(v)/N(t)*100))):0;
const weekStart=d=>{const x=new Date(d+"T00:00:00"),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return x};
const inWeek=d=>{const s=weekStart(today()),e=new Date(s);e.setDate(s.getDate()+7);const x=new Date(d+"T12:00:00");return x>=s&&x<e};
const daysUntil=d=>d?Math.ceil((new Date(d+"T00:00:00")-new Date(today()+"T00:00:00"))/86400000):null;
const outNum=v=>{const m=String(v??"").match(/-?\d+(\.\d+)?/);return m?Number(m[0]):null};
function sample(){
 const now=new Date().toISOString(),A="case-a",B="case-b",C="case-c";
 const cases=[
  [A,"Case A · Stroke UL","Stroke","Outpatient","Upper limb","Improving","Improve reach, grasp and release for independent meal preparation.","Reduce compensatory trunk movement; increase home-task carryover.",180,900,3,ago(-7),"Neurorehab therapist","Activity limitation: meal preparation. Participation goal: prepare a simple breakfast.","Monitor fatigue and shoulder discomfort."],
  [B,"Case B · Balance","Frailty / falls risk","Community","Balance","In progress","Improve safe sit-to-stand transfer and confidence walking indoors.","Reduce fear of falling; increase caregiver-supported practice.",120,500,3,ago(1),"Community rehabilitation team","Activity limitation: transfers and indoor walking. Participation goal: bedroom to dining area.","Use support surface for standing tasks."],
  [C,"Case C · SCI ADL","Spinal cord injury","Home programme","ADL / participation","Improving","Increase wheelchair-to-bed transfer independence and morning self-care participation.","Improve trunk control; reduce caregiver lifting burden.",150,650,3,ago(-14),"Home rehabilitation clinician","Activity limitation: transfer and self-care. Environmental factor: bed and bathroom setup.","Monitor skin integrity and avoid repeated shear."]
 ].map(x=>({id:x[0],label:x[1],diagnosis:x[2],phase:x[3],domain:x[4],goalStatus:x[5],primaryGoal:x[6],secondaryGoals:x[7],weeklyMinutes:x[8],weeklyReps:x[9],minimumQuality:x[10],reviewDate:x[11],clinician:x[12],icfFrame:x[13],precautions:x[14],createdAt:now,updatedAt:now}));
 const S=(caseId,d,setting,task,min,act,reps,q,f,p,assist,challenge,spec,carry,home,rest,notes)=>({id:uid("session"),caseId,date:ago(d),setting,task,minutes:min,activeMinutes:act,reps,quality:q,fatigue:f,pain:p,assistance:assist,challenge,specificity:spec,carryover:carry,homeAdherence:home,restBreaks:rest,notes,createdAt:now});
 const sessions=[
  S(A,0,"Clinic","Reach and grasp cups",40,34,185,4,5,2,"Verbal cueing","Appropriate","Directly linked to functional goal","Partial","Moderate",3,"Improved shoulder control after short rests."),
  S(A,1,"Home","Kitchen-object transfer practice",30,24,120,3,6,3,"Caregiver assist","Appropriate","Directly linked to functional goal","Yes, in daily activity","High",2,"Used practice during snack preparation."),
  S(A,3,"Clinic","Grasp-release with variable objects",35,29,155,3,5,2,"Verbal cueing","Appropriate","Directly linked to functional goal","Partial","Moderate",2,"Better thumb positioning with visual targets."),
  S(A,5,"Tele-rehab","Home reaching routine",25,18,90,3,6,4,"Caregiver assist","Appropriate","Partially linked to functional goal","Partial","Moderate",2,"Simplified routine for home use."),
  S(A,8,"Clinic","Tabletop reach sequencing",40,30,145,3,5,2,"Manual assist","Appropriate","Directly linked to functional goal","Not assessed","Moderate",3,"Baseline practice block."),
  S(A,11,"Clinic","Assisted opening containers",35,24,105,2,7,4,"Manual assist","Too difficult","Directly linked to functional goal","No","Low",4,"Task too difficult; grade next version."),
  S(B,0,"Community","Sit-to-stand and stepping",30,20,82,2,8,1,"Caregiver assist","Too difficult","Directly linked to functional goal","No","Low",5,"High fatigue; safety review recommended."),
  S(B,2,"Home","Supported sit-to-stand practice",25,16,68,3,7,0,"Caregiver assist","Appropriate","Directly linked to functional goal","Partial","Moderate",4,"Caregiver cueing improved confidence."),
  S(B,4,"Community","Indoor walking turns",30,18,55,2,8,1,"Caregiver assist","Too difficult","Directly linked to functional goal","No","Low",5,"Turns remain unstable; lower challenge."),
  S(B,6,"Clinic","Static balance and weight shift",35,24,95,3,6,0,"Manual assist","Appropriate","Partially linked to functional goal","Partial","Moderate",3,"Better weight acceptance."),
  S(B,9,"Clinic","Chair rise with cueing",30,22,88,3,5,0,"Verbal cueing","Appropriate","Directly linked to functional goal","Partial","Moderate",3,"Consistent setup improved dose."),
  S(B,12,"Home","Home safety transfer routine",20,12,42,2,7,0,"Caregiver assist","Too difficult","Unclear link","No","Low",5,"Home routine needs simplification."),
  S(C,1,"Home","Wheelchair-to-bed transfer components",45,34,135,4,4,1,"Verbal cueing","Appropriate","Directly linked to functional goal","Yes, in daily activity","High",3,"Reduced caregiver lift."),
  S(C,2,"Home","Trunk control and reach for self-care",35,27,118,4,4,1,"Verbal cueing","Appropriate","Directly linked to functional goal","Partial","High",2,"Improved midline recovery."),
  S(C,4,"Clinic","Sliding board setup and transfer",45,32,126,3,5,1,"Manual assist","Appropriate","Directly linked to functional goal","Partial","Moderate",3,"Setup sequence more consistent."),
  S(C,6,"Home","Bed mobility and pressure relief",30,22,98,3,5,2,"Verbal cueing","Appropriate","Partially linked to functional goal","Yes, in daily activity","High",2,"Reported easier morning routine."),
  S(C,9,"Clinic","Transfer rehearsal with caregiver",40,28,102,3,5,2,"Caregiver assist","Appropriate","Directly linked to functional goal","Partial","Moderate",3,"Caregiver body mechanics improved."),
  S(C,13,"Home","Morning self-care sequence",30,20,72,2,6,2,"Caregiver assist","Too difficult","Directly linked to functional goal","No","Moderate",4,"Split long routine into shorter blocks.")
 ];
 const O=(id,caseId,name,base,current,target,date,direction,note)=>({id,caseId,name,baseline:base,current,target,date:ago(date),direction,note,createdAt:now});
 const outcomes=[O("o-a1",A,"ARAT","21 points","32 points","42 points",0,"Higher is better","Improved grasp and release consistency."),O("o-a2",A,"Patient-specific goal","2/10","5/10","8/10",1,"Higher is better","Snack preparation with affected arm involvement."),O("o-b1",B,"TUG","29 sec","24 sec","18 sec",0,"Lower is better","Walking aid used; close supervision maintained."),O("o-b2",B,"5x Sit-to-Stand","38 sec","31 sec","24 sec",2,"Lower is better","Quality variable when fatigued."),O("o-c1",C,"Transfer independence","30%","58%","75%",1,"Higher is better","Transfer steps completed without physical assist."),O("o-c2",C,"Caregiver lift burden","8/10","5/10","3/10",2,"Lower is better","Caregiver-rated exertion during morning transfer.")];
 return {schemaVersion:3,cases,sessions,outcomes,exports:[]};
}
function normal(x){if(!x||!Array.isArray(x.cases)||!Array.isArray(x.sessions))return null;return{schemaVersion:3,cases:x.cases.map(c=>({id:c.id||uid("case"),label:c.label||"Untitled programme",diagnosis:c.diagnosis||"Other neurological condition",phase:c.phase||"Outpatient",domain:c.domain||"Mixed programme",goalStatus:c.goalStatus||"In progress",primaryGoal:c.primaryGoal||"Functional goal not specified.",secondaryGoals:c.secondaryGoals||"",weeklyMinutes:N(c.weeklyMinutes,180),weeklyReps:N(c.weeklyReps,900),minimumQuality:N(c.minimumQuality,3),reviewDate:c.reviewDate||today(),clinician:c.clinician||"",icfFrame:c.icfFrame||"",precautions:c.precautions||"",createdAt:c.createdAt||new Date().toISOString(),updatedAt:c.updatedAt||c.createdAt||new Date().toISOString()})),sessions:x.sessions.map(s=>({id:s.id||uid("session"),caseId:s.caseId||x.cases[0]?.id||"",date:s.date||today(),setting:s.setting||"Clinic",task:s.task||"Therapy session",minutes:N(s.minutes,30),activeMinutes:N(s.activeMinutes??s.minutes,25),reps:N(s.reps,100),quality:N(s.quality,3),fatigue:N(s.fatigue,4),pain:N(s.pain,0),assistance:s.assistance||"Mixed assist",challenge:s.challenge||"Appropriate",specificity:s.specificity||"Partially linked to functional goal",carryover:s.carryover||"Not assessed",homeAdherence:s.homeAdherence||"Not reported",restBreaks:N(s.restBreaks,1),notes:s.notes||"",createdAt:s.createdAt||new Date().toISOString()})),outcomes:Array.isArray(x.outcomes)?x.outcomes.map(o=>({id:o.id||uid("outcome"),caseId:o.caseId||x.cases[0]?.id||"",name:o.name||"Outcome measure",baseline:o.baseline||"",current:o.current||"",target:o.target||"",date:o.date||today(),direction:o.direction||"Higher is better",note:o.note||"",createdAt:o.createdAt||new Date().toISOString()})):[],exports:Array.isArray(x.exports)?x.exports:[]}}
function load(){for(const k of [APP_KEY,"neurorehabDoseTracker.v2"]){try{const s=normal(JSON.parse(localStorage.getItem(k)));if(s)return s}catch{}}return sample()}
let state=load();
const save=()=>localStorage.setItem(APP_KEY,JSON.stringify(state));
const getCase=id=>state.cases.find(c=>c.id===id);
const selected=()=>$("reviewCaseFilter")?.value&&$("reviewCaseFilter").value!=="all"?$("reviewCaseFilter").value:null;
const scope=()=>selected()?state.cases.filter(c=>c.id===selected()):state.cases;
const sessionsFor=id=>state.sessions.filter(s=>s.caseId===id);
const weeklyFor=id=>sessionsFor(id).filter(s=>inWeek(s.date));
const outcomesFor=id=>state.outcomes.filter(o=>o.caseId===id);
function stats(c){const w=weeklyFor(c.id),all=sessionsFor(c.id),active=w.reduce((a,s)=>a+N(s.activeMinutes),0),sched=w.reduce((a,s)=>a+N(s.minutes),0),reps=w.reduce((a,s)=>a+N(s.reps),0),ass=w.filter(s=>s.carryover!=="Not assessed"),pos=ass.filter(s=>s.carryover==="Yes, in daily activity"||s.carryover==="Partial");return{w,all,active,sched,reps,quality:avg(w.map(s=>s.quality)),fatigue:avg(w.map(s=>s.fatigue)),pain:avg(w.map(s=>s.pain)),carryAss:ass.length,carryPos:pos.length,carryRate:ass.length?Math.round(pos.length/ass.length*100):0,hard:w.filter(s=>s.challenge==="Too difficult"),lowHome:w.filter(s=>s.homeAdherence==="Low"),hiPain:w.filter(s=>N(s.pain)>=7),hiFatigue:w.filter(s=>N(s.fatigue)>=8&&N(s.quality)<=2),unclear:w.filter(s=>s.specificity==="Unclear link"),reviewDue:daysUntil(c.reviewDate),mPct:pct(active,c.weeklyMinutes),rPct:pct(reps,c.weeklyReps)}}
function review(c){const s=stats(c),r=[];if(!s.w.length)r.push(["warning","No session logged this week","No current-week session has been recorded.","Check whether therapy occurred but was not recorded or whether continuity has been lost."]);if(s.active<N(c.weeklyMinutes)*.5)r.push(["warning","Active practice below half of target",`${s.active} active minutes against a ${c.weeklyMinutes} minute target.`,"Review setup time, fatigue, staffing, motivation and home-practice feasibility."]);if(s.reps<N(c.weeklyReps)*.5)r.push(["warning","Repetition volume below half of target",`${s.reps} reps against a ${c.weeklyReps} rep target.`,"Consider shorter bouts, simpler tasks, assisted practice or clearer home practice."]);if(s.hiFatigue.length)r.push(["risk","High fatigue with low quality",`${s.hiFatigue.length} session(s) show fatigue >=8/10 and quality <=2/5.`,"Review rest intervals, compensation, safety and dose tolerance."]);if(s.hiPain.length)r.push(["risk","Pain needs review",`${s.hiPain.length} session(s) show pain >=7/10.`,"Review precautions, task selection, intensity and clinical assessment needs."]);if(s.carryAss>=2&&s.carryPos===0)r.push(["warning","No functional carryover",`${s.carryAss} assessed sessions with no full or partial carryover.`,"Review task specificity, home environment, patient goals and caregiver support."]);if(s.hard.length>=2)r.push(["warning","Challenge may be too high",`${s.hard.length} session(s) marked Too difficult.`,"Grade the task or increase assistance before chasing more volume."]);if(s.lowHome.length>=2)r.push(["warning","Home adherence is low",`${s.lowHome.length} session(s) marked low home adherence.`,"Simplify the home task and review caregiver/environmental barriers."]);if(s.unclear.length)r.push(["info","Task specificity is unclear",`${s.unclear.length} session(s) had unclear goal linkage.`,"Clarify the functional bridge or revise the goal."]);if(s.reviewDue!==null&&s.reviewDue<=0)r.push(["warning","Programme review is due",`Review date: ${fmt(c.reviewDate)}.`,"Update goals, targets, precautions and outcome measures."]);if(s.w.length&&s.active>=N(c.weeklyMinutes)&&s.reps>=N(c.weeklyReps)&&s.quality>=N(c.minimumQuality))r.push(["good","Dose and quality targets are being met",`${s.active} min, ${s.reps} reps, quality ${s.quality.toFixed(1)}/5.`,"Check whether the gains are transferring into outcomes and daily activity."]);return(r.length?r:[["good","No major review flags","Current entries do not cross rule-based thresholds.","Continue collecting dose, quality, fatigue, pain, carryover and outcome data."]]).map(x=>({severity:x[0],title:x[1],trigger:x[2],review:x[3]}))}
const allReviews=()=>state.cases.length?scope().flatMap(review):[{severity:"warning",title:"No programme created",trigger:"The app has no case/programme yet.",review:"Create a programme first, then add sessions and outcome measures."}];
function renderSelectors(){const opts=state.cases.map(c=>`<option value="${c.id}">${E(c.label)}</option>`).join(""),empty=`<option value="">Create a programme first</option>`;if($("sessionCaseId"))$("sessionCaseId").innerHTML=opts||empty;if($("outcomeCaseId"))$("outcomeCaseId").innerHTML=opts||empty;const cur=$("reviewCaseFilter")?.value||"all";if($("reviewCaseFilter")){$("reviewCaseFilter").innerHTML=`<option value="all">All cases</option>${opts}`;$("reviewCaseFilter").value=cur==="all"||state.cases.some(c=>c.id===cur)?cur:"all"}}
function renderStats(){const ps=scope(),w=ps.flatMap(c=>weeklyFor(c.id)),min=w.reduce((a,s)=>a+N(s.activeMinutes),0),reps=w.reduce((a,s)=>a+N(s.reps),0),tMin=ps.reduce((a,c)=>a+N(c.weeklyMinutes),0),tReps=ps.reduce((a,c)=>a+N(c.weeklyReps),0);$("minutesThisWeek").textContent=min;$("repsThisWeek").textContent=reps;$("avgQuality").textContent=avg(w.map(s=>s.quality)).toFixed(1);$("casesNeedingReview").textContent=ps.filter(c=>review(c).some(i=>i.severity==="warning"||i.severity==="risk")).length;$("minutesTargetLabel").textContent=`Target: ${tMin} min · ${pct(min,tMin)}%`;$("repsTargetLabel").textContent=`Target: ${tReps} reps · ${pct(reps,tReps)}%`}
function renderProgrammes(){const el=$("programmeList");if(!el)return;if(!state.cases.length){el.innerHTML=`<p class="empty">No programmes yet. Load sample data or create a programme.</p>`;return}el.innerHTML=state.cases.map(c=>{const s=stats(c),flag=review(c).find(i=>i.severity==="risk")||review(c).find(i=>i.severity==="warning")||review(c)[0];return`<article class="programme-card"><div class="session-top"><div><h3>${E(c.label)}</h3><p>${E(c.diagnosis)} · ${E(c.phase)} · ${E(c.domain)}</p></div><span class="badge ${flag.severity}">${E(flag.severity==="good"?"On track":flag.severity)}</span></div><p class="programme-goal">${E(c.primaryGoal)}</p><div class="mini-metrics"><span>${s.active}/${c.weeklyMinutes} min</span><span>${s.reps}/${c.weeklyReps} reps</span><span>Quality ${s.quality?s.quality.toFixed(1):"0.0"}/5</span></div><button class="secondary mini-button edit-programme" data-id="${c.id}">Edit programme</button></article>`}).join("");document.querySelectorAll(".edit-programme").forEach(b=>b.onclick=()=>editProgramme(b.dataset.id))}
function renderTable(){if(!state.cases.length){$("caseTable").innerHTML=`<tr><td colspan="8" class="empty">No programmes yet.</td></tr>`;return}$("caseTable").innerHTML=state.cases.map(c=>{const s=stats(c),flag=review(c).find(i=>i.severity==="risk")||review(c).find(i=>i.severity==="warning")||review(c)[0];return`<tr><td><strong>${E(c.label)}</strong><br><span>${E(c.diagnosis)} · ${E(c.phase)}</span></td><td>${E(c.primaryGoal)}</td><td>${s.active}/${c.weeklyMinutes} min<br>${s.reps}/${c.weeklyReps} reps</td><td>${s.quality?s.quality.toFixed(1):"0.0"}/5</td><td>${s.fatigue?s.fatigue.toFixed(1):"0.0"}/10</td><td>${s.pain?s.pain.toFixed(1):"0.0"}/10</td><td>${s.carryAss?`${s.carryRate}%`:"Not assessed"}</td><td><span class="badge ${flag.severity}">${E(flag.title)}</span></td></tr>`}).join("")}
function renderInsights(){$("insights").innerHTML=allReviews().map(i=>`<article class="insight ${i.severity}"><div class="insight-top"><strong>${E(i.title)}</strong><span class="badge ${i.severity}">${E(i.severity==="risk"?"Review recommended":i.severity)}</span></div><p><b>Trigger:</b> ${E(i.trigger)}</p><p><b>Clinician review:</b> ${E(i.review)}</p></article>`).join("")}
function renderSessions(){const data=(selected()?state.sessions.filter(s=>s.caseId===selected()):state.sessions).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$("sessionsList").innerHTML=data.length?data.slice(0,24).map(s=>`<article class="session-item"><div class="session-top"><div><div class="session-title">${E(s.task)} · ${E(getCase(s.caseId)?.label||"Unknown case")}</div><div class="session-meta">${fmt(s.date)} · ${E(s.setting)}<br>active ${s.activeMinutes} min / scheduled ${s.minutes} min · ${s.reps} reps · quality ${s.quality}/5 · fatigue ${s.fatigue}/10 · pain ${s.pain}/10<br>${E(s.assistance)} · ${E(s.challenge)} · carryover: ${E(s.carryover)} · home: ${E(s.homeAdherence)}</div></div><button class="delete-session danger" data-id="${s.id}">Delete</button></div>${s.notes?`<p class="session-notes">${E(s.notes)}</p>`:""}</article>`).join(""):`<p class="empty">No sessions saved yet.</p>`;document.querySelectorAll(".delete-session").forEach(b=>b.onclick=()=>{state.sessions=state.sessions.filter(s=>s.id!==b.dataset.id);save();render()})}
function renderOutcomeCards(data){const el=$("outcomeTrajectoryChart");if(!el)return;if(!data.length){el.innerHTML=`<p class="empty">Outcome trajectory charts appear after sample data or recorded measures are available.</p>`;return}el.innerHTML=data.map(o=>{const b=outNum(o.baseline),c=outNum(o.current),t=outNum(o.target);let p=0;if(b!==null&&c!==null&&t!==null&&b!==t)p=o.direction==="Lower is better"?pct(b-c,b-t):pct(c-b,t-b);return`<article class="outcome-card"><div class="outcome-top"><strong>${E(o.name)}</strong><span>${E(getCase(o.caseId)?.label||"Case")}</span></div><div class="trajectory"><span>Baseline<br><b>${E(o.baseline||"—")}</b></span><span>Current<br><b>${E(o.current||"—")}</b></span><span>Target<br><b>${E(o.target||"—")}</b></span></div><div class="progress"><div class="bar" style="width:${p}%"></div></div><small>${p}% of target trajectory · ${E(o.direction)}</small></article>`}).join("")}
function renderOutcomes(){const data=(selected()?state.outcomes.filter(o=>o.caseId===selected()):state.outcomes).sort((a,b)=>String(b.date).localeCompare(String(a.date)));renderOutcomeCards(data);$("outcomesList").innerHTML=data.length?data.map(o=>`<article class="session-item"><div class="session-top"><div><div class="session-title">${E(o.name)} · ${E(getCase(o.caseId)?.label||"Unknown case")}</div><div class="session-meta">${fmt(o.date)} · baseline: ${E(o.baseline||"—")} · current: ${E(o.current||"—")} · target: ${E(o.target||"—")} · ${E(o.direction)}</div></div><button class="delete-outcome danger" data-id="${o.id}">Delete</button></div>${o.note?`<p class="session-notes">${E(o.note)}</p>`:""}</article>`).join(""):`<p class="empty">No outcome measures recorded yet.</p>`;document.querySelectorAll(".delete-outcome").forEach(b=>b.onclick=()=>{state.outcomes=state.outcomes.filter(o=>o.id!==b.dataset.id);save();render()})}
function charts(){const ps=scope();$("doseChart").innerHTML=ps.length?ps.map(c=>{const s=stats(c);return`<div class="chart-row"><span>${E(c.label)}</span><div class="dual-bars"><i class="bar-minutes" style="width:${s.mPct}%"></i><i class="bar-reps" style="width:${s.rPct}%"></i></div><b>${s.mPct}% min · ${s.rPct}% reps</b></div>`}).join(""):`<p class="empty">No programme data available.</p>`;const w=ps.flatMap(c=>weeklyFor(c.id)),act=w.reduce((a,s)=>a+N(s.activeMinutes),0),sch=w.reduce((a,s)=>a+N(s.minutes),0),ap=pct(act,sch);$("doseChartSummary").textContent=`${act} active minutes logged this week across ${ps.length} programme(s).`;$("activeScheduledChart").innerHTML=`<div class="stacked-bar"><span class="active" style="width:${ap}%"></span><span class="inactive" style="width:${100-ap}%"></span></div><div class="legend"><span><i class="dot active-dot"></i>Active ${act} min</span><span><i class="dot inactive-dot"></i>Setup/rest ${Math.max(0,sch-act)} min</span></div>`;$("activeScheduledSummary").textContent=sch?`${ap}% of scheduled time became active practice this week.`:"No scheduled time recorded this week.";const yes=w.filter(s=>s.carryover==="Yes, in daily activity").length,part=w.filter(s=>s.carryover==="Partial").length,no=w.filter(s=>s.carryover==="No").length,not=w.filter(s=>s.carryover==="Not assessed").length,total=Math.max(1,w.length),d1=yes/total*360,d2=(yes+part)/total*360,d3=(yes+part+no)/total*360;$("carryoverChart").innerHTML=`<div class="donut" style="background:conic-gradient(var(--ok) 0deg ${d1}deg,var(--accent) ${d1}deg ${d2}deg,var(--risk) ${d2}deg ${d3}deg,rgba(255,255,255,.12) ${d3}deg 360deg)"><span>${Math.round((yes+part)/total*100)}%</span></div><div class="legend vertical"><span><i class="dot ok-dot"></i>Yes ${yes}</span><span><i class="dot active-dot"></i>Partial ${part}</span><span><i class="dot risk-dot"></i>No ${no}</span><span><i class="dot muted-dot"></i>Not assessed ${not}</span></div>`;$("carryoverSummary").textContent=`${yes+part} of ${w.length} current-week session(s) show full or partial carryover.`;lineChart(ps)}
function lineChart(ps){const data=ps.flatMap(c=>sessionsFor(c.id)).sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(-10),el=$("toleranceChart");if(!data.length){el.innerHTML=`<p class="empty">No sessions available for tolerance trend.</p>`;return}const W=680,H=220,P=28,x=i=>data.length===1?W/2:P+i*(W-P*2)/(data.length-1),y5=v=>H-P-(N(v)-1)/4*(H-P*2),y10=v=>H-P-N(v)/10*(H-P*2),poly=(pts,cl)=>`<polyline class="${cl}" points="${pts.map(p=>`${p.x},${p.y}`).join(" ")}"/>`;const q=data.map((s,i)=>({x:x(i),y:y5(s.quality)})),f=data.map((s,i)=>({x:x(i),y:y10(s.fatigue)})),p=data.map((s,i)=>({x:x(i),y:y10(s.pain)}));el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" class="line-chart"><line x1="${P}" y1="${H-P}" x2="${W-P}" y2="${H-P}" class="axis"/><line x1="${P}" y1="${P}" x2="${P}" y2="${H-P}" class="axis"/>${poly(q,"line-quality")}${poly(f,"line-fatigue")}${poly(p,"line-pain")}${q.map(a=>`<circle cx="${a.x}" cy="${a.y}" r="4" class="point quality"/>`).join("")}${f.map(a=>`<circle cx="${a.x}" cy="${a.y}" r="4" class="point fatigue"/>`).join("")}${p.map(a=>`<circle cx="${a.x}" cy="${a.y}" r="4" class="point pain"/>`).join("")}</svg><div class="legend"><span><i class="dot quality-dot"></i>Quality</span><span><i class="dot fatigue-dot"></i>Fatigue</span><span><i class="dot pain-dot"></i>Pain</span></div>`;const l=data[data.length-1];$("toleranceSummary").textContent=`Latest session: quality ${l.quality}/5, fatigue ${l.fatigue}/10 and pain ${l.pain}/10.`}
function evidence(){const s=state.sessions,act=s.reduce((a,x)=>a+N(x.activeMinutes),0),sch=s.reduce((a,x)=>a+N(x.minutes),0),ass=s.filter(x=>x.carryover!=="Not assessed"),pos=ass.filter(x=>x.carryover==="Yes, in daily activity"||x.carryover==="Partial");const cards=[["Programmes",state.cases.length],["Sessions",s.length],["Outcome measures",state.outcomes.length],["Active practice",`${act} min`],["Practice conversion",sch?`${Math.round(act/sch*100)}%`:"—"],["Carryover rate",ass.length?`${Math.round(pos.length/ass.length*100)}%`:"Not assessed"],["Home-adherence entries",s.filter(x=>!["Not applicable","Not reported"].includes(x.homeAdherence)).length],["Review prompts",allReviews().filter(x=>x.severity!=="good").length]];$("evidenceSummary").innerHTML=cards.map(c=>`<div class="evidence-card"><span>${E(c[0])}</span><strong>${E(c[1])}</strong></div>`).join("")}
function note(){return scope().map(c=>{const s=stats(c),outs=outcomesFor(c.id),rv=review(c).slice(0,5);return`Weekly Neurorehabilitation Progress Note\n\nCase: ${c.label}\nPathway: ${c.diagnosis} · ${c.phase} · ${c.domain}\nGoal status: ${c.goalStatus}\nResponsible clinician: ${c.clinician||"Not specified"}\nPrimary functional goal: ${c.primaryGoal}\nSecondary goals: ${c.secondaryGoals||"Not specified"}\nICF / participation frame: ${c.icfFrame||"Not specified"}\nPrecautions / boundaries: ${c.precautions||"Not specified"}\n\nDose summary, current week:\n- Sessions: ${s.w.length}\n- Active practice minutes: ${s.active} / ${c.weeklyMinutes}\n- Scheduled minutes: ${s.sched}\n- Repetitions: ${s.reps} / ${c.weeklyReps}\n- Average movement quality: ${s.quality?s.quality.toFixed(1):"0.0"} / 5\n- Average fatigue: ${s.fatigue?s.fatigue.toFixed(1):"0.0"} / 10\n- Average pain/discomfort: ${s.pain?s.pain.toFixed(1):"0.0"} / 10\n- Functional carryover: ${s.carryAss?`${s.carryPos}/${s.carryAss} assessed sessions`:"Not assessed"}\n\nOutcome measures:\n${outs.length?outs.map(o=>`- ${o.name}: baseline ${o.baseline||"—"}, current ${o.current||"—"}, target ${o.target||"—"} (${fmt(o.date)})`).join("\n"):"- No outcome measures recorded."}\n\nAI-Generated Review for clinician interpretation:\n${rv.map(i=>`- ${i.title}: ${i.review}`).join("\n")}\n\nDocumentation note:\nThis generated note is a draft for clinician review and does not make treatment decisions.`}).join("\n\n---\n\n")||"No programme data available."}
function report(){const ps=scope();$("reportPreview").innerHTML=ps.length?`<div class="report-header"><div><h3>Neurorehabilitation Dose Review</h3><p>Generated ${fmt(today())} · ${ps.length} programme(s) in view</p></div><span class="badge info">Prototype report</span></div><div class="report-columns">${ps.map(c=>{const s=stats(c);return`<article class="report-case"><h3>${E(c.label)}</h3><p>${E(c.primaryGoal)}</p><div class="mini-metrics"><span>${s.mPct}% minute target</span><span>${s.rPct}% rep target</span><span>${s.carryAss?`${s.carryRate}% carryover`:"Carryover N/A"}</span></div></article>`}).join("")}</div><h3>Priority review prompts</h3><div class="report-prompts">${allReviews().slice(0,6).map(i=>`<div class="prompt-line"><span class="badge ${i.severity}">${E(i.severity)}</span><p><b>${E(i.title)}:</b> ${E(i.review)}</p></div>`).join("")}</div><pre>${E(note())}</pre>`:`<p class="empty">No programme data available.</p>`}
function render(){renderSelectors();renderStats();renderProgrammes();renderTable();renderInsights();renderSessions();renderOutcomes();charts();evidence();report()}
function editProgramme(id){const c=getCase(id);if(!c)return;[["caseId",c.id],["caseLabel",c.label],["diagnosis",c.diagnosis],["phase",c.phase],["domain",c.domain],["goalStatus",c.goalStatus],["primaryGoal",c.primaryGoal],["secondaryGoals",c.secondaryGoals],["weeklyMinutes",c.weeklyMinutes],["weeklyReps",c.weeklyReps],["minimumQuality",c.minimumQuality],["reviewDate",c.reviewDate],["clinician",c.clinician],["icfFrame",c.icfFrame],["precautions",c.precautions]].forEach(x=>{if($(x[0]))$(x[0]).value=x[1]??""});tab("programmes");$("caseLabel")?.focus()}
function saveProgramme(e){e.preventDefault();const id=$("caseId").value||uid("case"),old=getCase(id);const c={id,label:$("caseLabel").value.trim(),diagnosis:$("diagnosis").value,phase:$("phase").value,domain:$("domain").value,goalStatus:$("goalStatus").value,primaryGoal:$("primaryGoal").value.trim(),secondaryGoals:$("secondaryGoals").value.trim(),weeklyMinutes:N($("weeklyMinutes").value),weeklyReps:N($("weeklyReps").value),minimumQuality:N($("minimumQuality").value),reviewDate:$("reviewDate").value,clinician:$("clinician").value.trim(),icfFrame:$("icfFrame").value.trim(),precautions:$("precautions").value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};state.cases=state.cases.filter(x=>x.id!==id).concat(c);save();e.target.reset();$("caseId").value="";$("reviewDate").value=today();render()}
function saveSession(e){e.preventDefault();if(!$("sessionCaseId").value)return alert("Create a programme before logging a session.");state.sessions.push({id:uid("session"),caseId:$("sessionCaseId").value,date:$("date").value,setting:$("setting").value,task:$("task").value.trim(),minutes:N($("minutes").value),activeMinutes:N($("activeMinutes").value),reps:N($("reps").value),quality:N($("quality").value),fatigue:N($("fatigue").value),pain:N($("pain").value),assistance:$("assistance").value,challenge:$("challenge").value,specificity:$("specificity").value,carryover:$("carryover").value,homeAdherence:$("homeAdherence").value,restBreaks:N($("restBreaks").value),notes:$("notes").value.trim(),createdAt:new Date().toISOString()});save();e.target.reset();defaults();render()}
function saveOutcome(e){e.preventDefault();if(!$("outcomeCaseId").value)return alert("Create a programme before recording an outcome.");state.outcomes.push({id:uid("outcome"),caseId:$("outcomeCaseId").value,name:$("outcomeName").value.trim(),baseline:$("baselineValue").value.trim(),current:$("currentValue").value.trim(),target:$("targetValue").value.trim(),date:$("outcomeDate").value||today(),direction:$("outcomeDirection").value,note:$("outcomeNote").value.trim(),createdAt:new Date().toISOString()});save();e.target.reset();$("outcomeDate").value=today();render()}
function defaults(){if($("date"))$("date").value=today();if($("reviewDate"))$("reviewDate").value=$("reviewDate").value||today();if($("outcomeDate"))$("outcomeDate").value=today();[["minutes",30],["activeMinutes",25],["reps",100],["quality",3],["fatigue",4],["pain",0],["restBreaks",1]].forEach(x=>{if($(x[0]))$(x[0]).value=x[1]})}
const dl=(name,content,type="text/plain;charset=utf-8")=>{const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);state.exports.push({id:uid("export"),filename:name,createdAt:new Date().toISOString()});save();evidence()};
const csv=()=>{const h=["caseLabel","diagnosis","phase","primaryGoal","date","setting","task","scheduledMinutes","activeMinutes","repetitions","quality","fatigue","pain","assistance","challenge","specificity","carryover","homeAdherence","restBreaks","notes"],cell=v=>`"${String(v??"").replaceAll('"','""')}"`,rows=state.sessions.map(s=>{const c=getCase(s.caseId)||{};return[c.label,c.diagnosis,c.phase,c.primaryGoal,s.date,s.setting,s.task,s.minutes,s.activeMinutes,s.reps,s.quality,s.fatigue,s.pain,s.assistance,s.challenge,s.specificity,s.carryover,s.homeAdherence,s.restBreaks,s.notes].map(cell).join(",")});dl(`neurorehab-dose-tracker-${today()}.csv`,[h.join(","),...rows].join("\n"),"text/csv;charset=utf-8")};
const fhir=()=>{const entry=[];state.cases.forEach(c=>{entry.push({resource:{resourceType:"Patient",id:c.id,identifier:[{system:"https://zenkoh.github.io/neurorehab-dose-tracker/case",value:c.label}]}});entry.push({resource:{resourceType:"CarePlan",id:`careplan-${c.id}`,status:"active",intent:"plan",subject:{reference:`Patient/${c.id}`},title:`Neurorehabilitation programme: ${c.domain}`,description:c.primaryGoal}})});state.sessions.forEach(s=>[["active-practice-minutes","Active practice minutes",s.activeMinutes,"min"],["repetitions","Therapy repetitions",s.reps,"count"],["movement-quality","Movement quality score",s.quality,"score"],["fatigue","Fatigue rating",s.fatigue,"score"],["pain","Pain/discomfort rating",s.pain,"score"]].forEach(m=>entry.push({resource:{resourceType:"Observation",id:`${m[0]}-${s.id}`,status:"final",subject:{reference:`Patient/${s.caseId}`},effectiveDateTime:s.date,code:{text:m[1]},valueQuantity:{value:N(m[2]),unit:m[3]}}})));state.outcomes.forEach(o=>entry.push({resource:{resourceType:"Observation",id:`outcome-${o.id}`,status:"final",subject:{reference:`Patient/${o.caseId}`},effectiveDateTime:o.date,code:{text:o.name},valueString:`Baseline: ${o.baseline||"—"}; current: ${o.current||"—"}; target: ${o.target||"—"}`}}));dl(`neurorehab-fhir-shaped-export-${today()}.json`,JSON.stringify({resourceType:"Bundle",type:"collection",timestamp:new Date().toISOString(),entry},null,2),"application/json;charset=utf-8")};
function restore(e){const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const imported=normal(JSON.parse(r.result));if(!imported)return alert("This does not look like a valid backup.");state=imported;save();render()}catch{alert("Could not read this JSON backup.")}finally{e.target.value=""}};r.readAsText(file)}
function tab(name){document.querySelectorAll(".tab-button").forEach(b=>{const on=b.dataset.tab===name;b.classList.toggle("active",on);b.setAttribute("aria-selected",on?"true":"false")});document.querySelectorAll(".tab-panel").forEach(p=>{const on=p.id===name;p.classList.toggle("active",on);p.hidden=!on});history.replaceState?.(null,"",`#${name}`);window.scrollTo({top:0,behavior:"smooth"})}
function bind(){document.querySelectorAll(".tab-button").forEach(b=>{b.type="button";b.onclick=()=>tab(b.dataset.tab)});$("caseForm")?.addEventListener("submit",saveProgramme);$("sessionForm")?.addEventListener("submit",saveSession);$("outcomeForm")?.addEventListener("submit",saveOutcome);$("reviewCaseFilter")?.addEventListener("change",render);$("loadSampleBtn")?.addEventListener("click",()=>{state=sample();save();render()});$("exportCsvBtn")?.addEventListener("click",csv);$("exportNoteBtn")?.addEventListener("click",()=>dl(`neurorehab-progress-note-${today()}.txt`,note()));$("exportFhirBtn")?.addEventListener("click",fhir);$("backupBtn")?.addEventListener("click",()=>dl(`neurorehab-dose-tracker-backup-${today()}.json`,JSON.stringify(state,null,2),"application/json;charset=utf-8"));$("restoreInput")?.addEventListener("change",restore);$("clearBtn")?.addEventListener("click",()=>{if(confirm("Clear all local data from this browser?")){state={schemaVersion:3,cases:[],sessions:[],outcomes:[],exports:[]};save();render()}})}
bind();defaults();tab(document.getElementById(location.hash.replace("#","")||"overview")?location.hash.replace("#","")||"overview":"overview");render();